In [1]:
import pandas as pd
import numpy as np
# nl1909 = pd.read_csv("201909_new.csv")
level = 'ADM2_EN'
nl1909 = pd.read_csv("201607_adm2.csv")[[level,'layer']]
nl1910 = pd.read_csv("201608_adm2.csv")[[level,'layer']]
nl1911 = pd.read_csv("201609_adm2.csv")[[level,'layer']]
nl1912 = pd.read_csv("201610_adm2.csv")[[level,'layer']]
nl2001 = pd.read_csv("201611_adm2.csv")[[level,'layer']]
nl2002 = pd.read_csv("201612_adm2.csv")[[level,'layer']]
nl2007 = pd.read_csv("201701_adm2.csv")[[level,'layer']]
nl2008 = pd.read_csv("201702_adm2.csv")[[level,'layer']]
nl2009 = pd.read_csv("201703_adm2.csv")[[level,'layer']]
nl2010 = pd.read_csv("201704_adm2.csv")[[level,'layer']]
nl2011 = pd.read_csv("201705_adm2.csv")[[level,'layer']]
nl2012 = pd.read_csv("201706_adm2.csv")[[level,'layer']]
test = pd.read_stata("GSEC1.dta",convert_categoricals=False)

In [2]:
GSEC1_need = test[['hhid','s1aq2a','s1aq4a','s1aq5a','year','month','day','finalwgt','mnts','urban']].copy()
GSEC1_need['mnts'].replace({2:0},inplace=True)
GSEC1_need['District'] = GSEC1_need['s1aq2a'].str.lower()
nl1909[['year','month']] = 2016,7
nl1910[['year','month']] = 2016,8
nl1911[['year','month']] = 2016,9
nl1912[['year','month']] = 2016,10
nl2001[['year','month']] = 2016,11
nl2002[['year','month']] = 2016,12
nl2007[['year','month']] = 2017,1
nl2008[['year','month']] = 2017,2
nl2009[['year','month']] = 2017,3
nl2010[['year','month']] = 2017,4
nl2011[['year','month']] = 2017,5
nl2012[['year','month']] = 2017,6
nl1909['District'] = nl1909[level].str.lower()
nl1910['District'] = nl1910[level].str.lower()
nl1911['District'] = nl1911[level].str.lower()
nl1912['District'] = nl1912[level].str.lower()
nl2001['District'] = nl2001[level].str.lower()
nl2002['District'] = nl2002[level].str.lower()
nl2007['District'] = nl2007[level].str.lower()
nl2008['District'] = nl2008[level].str.lower()
nl2009['District'] = nl2009[level].str.lower()
nl2010['District'] = nl2010[level].str.lower()
nl2011['District'] = nl2011[level].str.lower()
nl2012['District'] = nl2012[level].str.lower()
res = pd.concat([nl1909,nl1910],axis=0)
lst = [nl1911,nl1912,nl2001,nl2002,nl2007,nl2008,nl2009,nl2010,nl2011,nl2012]
for i in lst: 
    res = pd.concat([res,i],axis=0)
GSEC1_nightlight = pd.merge(GSEC1_need,res,how='left',on=['District','year','month'])
GSEC1_nightlight.rename(columns={"layer":"NL_District"},inplace=True)

In [3]:
level = 'ADM3_EN'
level2 = 'ADM2_EN'
nl1909 = pd.read_csv("201607_adm3.csv")[[level,level2,'layer']]
nl1910 = pd.read_csv("201608_adm3.csv")[[level,level2,'layer']]
nl1911 = pd.read_csv("201609_adm3.csv")[[level,level2,'layer']]
nl1912 = pd.read_csv("201610_adm3.csv")[[level,level2,'layer']]
nl2001 = pd.read_csv("201611_adm3.csv")[[level,level2,'layer']]
nl2002 = pd.read_csv("201612_adm3.csv")[[level,level2,'layer']]
nl2007 = pd.read_csv("201701_adm3.csv")[[level,level2,'layer']]
nl2008 = pd.read_csv("201702_adm3.csv")[[level,level2,'layer']]
nl2009 = pd.read_csv("201703_adm3.csv")[[level,level2,'layer']]
nl2010 = pd.read_csv("201704_adm3.csv")[[level,level2,'layer']]
nl2011 = pd.read_csv("201705_adm3.csv")[[level,level2,'layer']]
nl2012 = pd.read_csv("201706_adm3.csv")[[level,level2,'layer']]
nl1909[['year','month']] = 2016,7
nl1910[['year','month']] = 2016,8
nl1911[['year','month']] = 2016,9
nl1912[['year','month']] = 2016,10
nl2001[['year','month']] = 2016,11
nl2002[['year','month']] = 2016,12
nl2007[['year','month']] = 2017,1
nl2008[['year','month']] = 2017,2
nl2009[['year','month']] = 2017,3
nl2010[['year','month']] = 2017,4
nl2011[['year','month']] = 2017,5
nl2012[['year','month']] = 2017,6
nl1909['County'] = nl1909[level].str.lower()
nl1910['County'] = nl1910[level].str.lower()
nl1911['County'] = nl1911[level].str.lower()
nl1912['County'] = nl1912[level].str.lower()
nl2001['County'] = nl2001[level].str.lower()
nl2002['County'] = nl2002[level].str.lower()
nl2007['County'] = nl2007[level].str.lower()
nl2008['County'] = nl2008[level].str.lower()
nl2009['County'] = nl2009[level].str.lower()
nl2010['County'] = nl2010[level].str.lower()
nl2011['County'] = nl2011[level].str.lower()
nl2012['County'] = nl2012[level].str.lower()
nl1909['District'] = nl1909[level2].str.lower()
nl1910['District'] = nl1910[level2].str.lower()
nl1911['District'] = nl1911[level2].str.lower()
nl1912['District'] = nl1912[level2].str.lower()
nl2001['District'] = nl2001[level2].str.lower()
nl2002['District'] = nl2002[level2].str.lower()
nl2007['District'] = nl2007[level2].str.lower()
nl2008['District'] = nl2008[level2].str.lower()
nl2009['District'] = nl2009[level2].str.lower()
nl2010['District'] = nl2010[level2].str.lower()
nl2011['District'] = nl2011[level2].str.lower()
nl2012['District'] = nl2012[level2].str.lower()
lsts = [nl1909,nl1910,nl1911,nl1912,nl2001,nl2002,nl2007,nl2008,nl2009,nl2010,nl2011,nl2012]
for j in lsts: 
    tr = j[j[['County','District']].duplicated(keep=False)].groupby('County').mean().reset_index().copy()
    for i in list(tr['County']):
        sh = j.loc[j['County']==i,'layer'].shape[0]
        j.loc[j['County']==i,'layer'] = tr[tr['County']==i]['layer'].values.repeat(sh)
res = pd.concat([nl1909,nl1910],axis=0)
lst = [nl1911,nl1912,nl2001,nl2002,nl2007,nl2008,nl2009,nl2010,nl2011,nl2012]
for i in lst: 
    res = pd.concat([res,i],axis=0)
    
GSEC1_nightlight['County'] = GSEC1_nightlight['s1aq4a'].str.lower()
res['County'].replace({'west budama (kisolo)':'west budama','kinkizi':'kinkiizi',
                         'bushenyi  municipality':'bushenyi-ishaka municipal','makindye ssabagabo municipality':'makindye ssabagabo munici',
                         'chekwi':'chekwii'},inplace=True)

GSEC1_output = pd.merge(GSEC1_nightlight,res[['layer','year','month','County','District']],how='left',on=['County','District','year','month'])
GSEC1_output.drop_duplicates('hhid',inplace=True)
GSEC1_output.rename(columns={"layer":"NL_County"},inplace=True)
GSEC1_output.drop(columns=['ADM2_EN'],inplace=True) 
GSEC1_output.dropna(subset=['year'],inplace=True)
s1 = GSEC1_output[GSEC1_output['NL_County'].isna()].copy()
GSEC1_output.loc[GSEC1_output['NL_County'].isna(),'NL_County'] = s1['NL_District']
GSEC1_output.to_csv("GSEC1_nl_dist.csv",index=False)

In [5]:
GSEC1_nightlight.to_csv("GSEC1_nl_dist.csv",index=False) #without imputation

In [2]:
# in the district level, full match 
county = list(set(test['s1aq2a']))
county_lower = [s.lower() for s in county]
county_lower.sort()
nlcounty = list(set(nl1909["ADM2_EN"]))
nlcounty_lower = [s.lower() for s in nlcounty]
nlcounty_lower.sort()
countyset = set(county_lower)
nlcountyset = set(nlcounty_lower)
diff_test_nl = list(countyset - nlcountyset)
# exdf = pd.DataFrame({"diff":diff_test_nl})
# exdf.to_csv("diffcounty.csv")
leftcounty = list(nlcountyset - countyset)
# exdf2 = pd.DataFrame({"diff":leftcounty})
# exdf2.to_csv("nlleftcounty.csv")
len(diff_test_nl)
# len(leftcounty)

0

In [22]:
# county and sub-county level also matches well 
county = list(set(test['s1aq5a']))
county_lower = [s.lower() for s in county]
county_lower.sort()
nlcounty = list(set(nl1909_3["ADM4_EN"]))
nlcounty_lower = [s.lower() for s in nlcounty]
nlcounty_lower.sort()
countyset = set(county_lower)
nlcountyset = set(nlcounty_lower)
# len(countyset - nlcountyset)
# len(nlcountyset - countyset)

diff_test_nl = list(countyset - nlcountyset)
exdf = pd.DataFrame({"diff":diff_test_nl})
# exdf.to_csv("diffsubcounty.csv")
leftcounty = list(nlcountyset - countyset)
exdf2 = pd.DataFrame({"diff":leftcounty})
# exdf2.to_csv("nlleftsubcounty.csv")

In [23]:
county = list(set(test['s1aq4a']))
county_lower = [s.lower() for s in county]
county_lower.sort()
nlcounty = list(set(nl1909_3["ADM3_EN"]))
nlcounty_lower = [s.lower() for s in nlcounty]
nlcounty_lower.sort()
countyset = set(county_lower)
nlcountyset = set(nlcounty_lower)
# len(countyset - nlcountyset)
# len(nlcountyset - countyset)

diff_test_nl = list(countyset - nlcountyset)
exdf = pd.DataFrame({"diff":diff_test_nl})
# exdf.to_csv("diffcounty.csv")
leftcounty = list(nlcountyset - countyset)
exdf2 = pd.DataFrame({"diff":leftcounty})
# exdf2.to_csv("nlleftcounty.csv")

In [21]:
countydataframe = pd.DataFrame({"UNHS":county_lower})
NLcountydataframe = pd.DataFrame({"NLdata":nlcounty_lower})

In [29]:
len(set(nl1909_3["ADM4_EN"]))

1455

In [31]:
len(set(test['s1aq5a']))

1056

In [3]:
len(set(nl1909_3["ADM3_EN"]))

194

In [37]:
len(set(test['s1aq4a']))

194

In [55]:
test.query("s1aq2a == 'KAMPALA'")

,hhid,interview__id,batch_id,s1aq9,s1aq3,s1aq1a,s1aq1b,s1aq2a,dc_2018,s1aq4a,...,region,regurb,prdp,mnts,nonresp,covid,reason,urban,hmult,poor_20
681,108601,3182af75d6654bfc8ae8e95c08018315,1086,1,Urban,KAMPALA,NaN,KAMPALA,102,KCCA,...,Central,11,Rest of the Country,Non-Mountainous,Completed,1,-2,1,972.384399,Non-poor
682,108602,f2fa72c9afb54de6bc4f2dfaf61021bc,1086,2,Urban,KAMPALA,NaN,KAMPALA,102,KCCA,...,Central,11,Rest of the Country,Non-Mountainous,Completed,1,-2,1,1929.991577,Non-poor
683,108603,fb941b0c12f94e07bb4c14ef8ec578c4,1086,3,Urban,KAMPALA,NaN,KAMPALA,102,KCCA,...,Central,1,Rest of the Country,Non-Mountainous,Not done,1,Entire household absent for extended period of...,1,NaN,NaN
684,108605,95703a9f472444cf8bd0ae7287050305,1086,5,Urban,KAMPALA,NaN,KAMPALA,102,KCCA,...,Central,11,Rest of the Country,Non-Mountainous,Completed,1,-2,1,1929.991577,Non-poor
685,108606,7e73315ae3d34200aba211e78d176210,1086,6,Urban,KAMPALA,NaN,KAMPALA,102,KCCA,...,Central,11,Rest of the Country,Non-Mountainous,Completed,1,-2,1,1929.991577,Non-poor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13030,67406,2e030250ae264710b10b3d92cafb913c,674,6,Urban,KAMPALA,NaN,KAMPALA,102,KCCA,...,Central,11,Rest of the Country,Non-Mountainous,Completed,1,-2,1,504.733978,Non-poor
13031,67407,28390919872e47e699a8cb74b62a15ef,674,7,Urban,KAMPALA,NaN,KAMPALA,102,KCCA,...,Central,11,Rest of the Country,Non-Mountainous,Completed,1,-2,1,1001.797546,Non-poor
13032,67408,6e60e769e8fb4f21a9036dae1c441ea7,674,8,Urban,KAMPALA,NaN,KAMPALA,102,KCCA,...,Central,11,Rest of the Country,Non-Mountainous,Completed,1,-2,1,1995.924683,Non-poor
13033,67409,bf8d0235bdc04afcba53ff142278a586,674,9,Urban,KAMPALA,NaN,KAMPALA,102,KCCA,...,Central,11,Rest of the Country,Non-Mountainous,Completed,1,-2,1,1001.797546,Non-poor
13034,67410,7d6f313b412c4ceb9c18c7dd983b77ef,674,10,Urban,KAMPALA,NaN,KAMPALA,102,KCCA,...,Central,1,Rest of the Country,Non-Mountainous,Not done,1,Dwelling vacant or address not a dwelling,1,NaN,NaN

In [27]:
str = "Namutumba Town Council"
str.upper()

'NAMUTUMBA TOWN COUNCIL'